/* tslint:disable */
/* eslint-disable */
/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedTransactionDTO,
    EmbeddedTransactionDTOFromJSON,
    EmbeddedTransactionDTOFromJSONTyped,
    EmbeddedTransactionDTOToJSON,
    NetworkTypeEnum,
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    PriceTransactionBodyDTO,
    PriceTransactionBodyDTOFromJSON,
    PriceTransactionBodyDTOFromJSONTyped,
    PriceTransactionBodyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface EmbeddedPriceTransactionDTO
 */
export interface EmbeddedPriceTransactionDTO {
    /**
     * Public key.
     * @type {string}
     * @memberof EmbeddedPriceTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version.
     * @type {number}
     * @memberof EmbeddedPriceTransactionDTO
     */
    version: number;
    /**
     * 
     * @type {NetworkTypeEnum}
     * @memberof EmbeddedPriceTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof EmbeddedPriceTransactionDTO
     */
    type: number;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof EmbeddedPriceTransactionDTO
     */
    blockHeight: string;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof EmbeddedPriceTransactionDTO
     */
    highPrice: string;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof EmbeddedPriceTransactionDTO
     */
    lowPrice: string;
}

export function EmbeddedPriceTransactionDTOFromJSON(json: any): EmbeddedPriceTransactionDTO {
    return EmbeddedPriceTransactionDTOFromJSONTyped(json, false);
}

export function EmbeddedPriceTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedPriceTransactionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': json['network'],
        'type': json['type'],
        'blockHeight': json['blockHeight'],
        'highPrice': json['highPrice'],
        'lowPrice': json['lowPrice'],
    };
}

export function EmbeddedPriceTransactionDTOToJSON(value?: EmbeddedPriceTransactionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'signerPublicKey': value.signerPublicKey,
        'version': value.version,
        'network': value.network,
        'type': value.type,
        'blockHeight': value.blockHeight,
        'highPrice': value.highPrice,
        'lowPrice': value.lowPrice,
    };
}


