/* tslint:disable */
/* eslint-disable */
/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NetworkTypeEnum,
    NetworkTypeEnumFromJSON,
    NetworkTypeEnumFromJSONTyped,
    NetworkTypeEnumToJSON,
    PriceTransactionBodyDTO,
    PriceTransactionBodyDTOFromJSON,
    PriceTransactionBodyDTOFromJSONTyped,
    PriceTransactionBodyDTOToJSON,
    TransactionDTO,
    TransactionDTOFromJSON,
    TransactionDTOFromJSONTyped,
    TransactionDTOToJSON,
} from './';

/**
 * Price Transaction.
 * @export
 * @interface PriceTransactionDTO
 */
export interface PriceTransactionDTO {
    /**
     * A number that allows uint 32 values.
     * @type {number}
     * @memberof PriceTransactionDTO
     */
    size: number;
    /**
     * Entity's signature generated by the signer.
     * @type {string}
     * @memberof PriceTransactionDTO
     */
    signature: string;
    /**
     * Public key.
     * @type {string}
     * @memberof PriceTransactionDTO
     */
    signerPublicKey: string;
    /**
     * Entity version.
     * @type {number}
     * @memberof PriceTransactionDTO
     */
    version: number;
    /**
     * 
     * @type {NetworkTypeEnum}
     * @memberof PriceTransactionDTO
     */
    network: NetworkTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof PriceTransactionDTO
     */
    type: number;
    /**
     * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
     * @type {string}
     * @memberof PriceTransactionDTO
     */
    maxFee: string;
    /**
     * Duration expressed in number of blocks.
     * @type {string}
     * @memberof PriceTransactionDTO
     */
    deadline: string;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof PriceTransactionDTO
     */
    blockHeight: string;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof PriceTransactionDTO
     */
    highPrice: string;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof PriceTransactionDTO
     */
    lowPrice: string;
}

export function PriceTransactionDTOFromJSON(json: any): PriceTransactionDTO {
    return PriceTransactionDTOFromJSONTyped(json, false);
}

export function PriceTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceTransactionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'size': json['size'],
        'signature': json['signature'],
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': json['network'],
        'type': json['type'],
        'maxFee': json['maxFee'],
        'deadline': json['deadline'],
        'blockHeight': json['blockHeight'],
        'highPrice': json['highPrice'],
        'lowPrice': json['lowPrice'],
    };
}

export function PriceTransactionDTOToJSON(value?: PriceTransactionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'size': value.size,
        'signature': value.signature,
        'signerPublicKey': value.signerPublicKey,
        'version': value.version,
        'network': value.network,
        'type': value.type,
        'maxFee': value.maxFee,
        'deadline': value.deadline,
        'blockHeight': value.blockHeight,
        'highPrice': value.highPrice,
        'lowPrice': value.lowPrice,
    };
}


