/* tslint:disable */
/* eslint-disable */
/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceTransactionBodyDTO
 */
export interface PriceTransactionBodyDTO {
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof PriceTransactionBodyDTO
     */
    blockHeight: string;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof PriceTransactionBodyDTO
     */
    highPrice: string;
    /**
     * A number that allows uint 64 values represented with a string.
     * @type {string}
     * @memberof PriceTransactionBodyDTO
     */
    lowPrice: string;
}

export function PriceTransactionBodyDTOFromJSON(json: any): PriceTransactionBodyDTO {
    return PriceTransactionBodyDTOFromJSONTyped(json, false);
}

export function PriceTransactionBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceTransactionBodyDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blockHeight': json['blockHeight'],
        'highPrice': json['highPrice'],
        'lowPrice': json['lowPrice'],
    };
}

export function PriceTransactionBodyDTOToJSON(value?: PriceTransactionBodyDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blockHeight': value.blockHeight,
        'highPrice': value.highPrice,
        'lowPrice': value.lowPrice,
    };
}


